/**
 * App actions mapped to the server permissions they require.
 *
 * Views, components and routes should always refer to an action from this file instead of
 * hardcoding a server permission, so that a permission change is a one line change here.
 *
 * The value is the permission expression evaluated by `hasPermission` of the user store.
 * It supports the `OR` and `AND` operators, and an empty value means the action is allowed
 * for every logged in user.
 */
export default {
  APP_ORDERS_VIEW: "ORDERMGR_VIEW OR ORD_SALES_ORDER_VIEW OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_ORDER_UPDATE: "ORDERMGR_UPDATE OR ORD_SALES_ORDER_EDIT OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_ORDER_CREATE: "ORDERMGR_CREATE OR ORD_SALES_ORDER_CREATE OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_ORDER_CANCEL: "ORD_SALES_ORDER_CNCL OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_ORDER_TASK_CREATE: "ORD_CRT_EVENT_VIEW OR COMM_EVNT_MENU_VIEW OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_ORDER_RETURN_VIEW: "ORDERMGR_RETURN OR ORD_SALES_RTN_VIEW OR ORD_SALES_RTN_ADMIN OR ORDERMGR_ADMIN",
  APP_ORDER_IDENTIFICATION_UPDATE: "ORDERMGR_ADMIN",
  APP_SWAP_ORDER: "MOVE_SO_ITEM OR ORDERMGR_UPDATE OR ORD_SALES_ORDER_EDIT OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_CUSTOMERS_VIEW: "RELATNSHIP_CUSTOMER_VIEW OR RELATNSHIP_CUSTOMER_ADMIN OR ORDERMGR_VIEW OR ORD_SALES_ORDER_ADMIN OR ORDERMGR_ADMIN",
  APP_CUSTOMER_CREATE: "RELATNSHIP_CUSTOMER_CREATE OR RELATNSHIP_CUSTOMER_ADMIN OR ORDERMGR_CREATE OR ORDERMGR_ADMIN",
  APP_PRODUCT_ASSOCIATION_UPDATE: "PIM_PRODUCT_CREATE OR PIM_PRODUCT_ADMIN",
  APP_PRODUCT_IDENTIFIER_UPDATE: "STOREFULFILLMENT_ADMIN",
  APP_COMMERCE_VIEW: "COMMERCEUSER_VIEW"
} as const satisfies Record<string, string>
